In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [2]:
'''Inputs: Measured peaks (S), peak efficiencies (ep), total efficiency (et)'''
PeakData = np.genfromtxt("Co-60 PEAKS.txt", comments="#", delimiter=",", filling_values='0')
Efficiencies = np.genfromtxt("efficiency.txt", comments="#", delimiter=",", filling_values='0')

# Order of matrices (number of energy levels, including the ground state)
w = len(PeakData[0])

'''PROVIDED VALUES'''
'''Source disintegration rate'''
rline = 0
r = np.array(PeakData[rline])
R = r.sum()
# R = 100
print("Source disintegration rate:", '\n', R)

'''Total Efficiency'''
Tline = rline+1
# print('Tline', Tline)
T = PeakData[Tline]
et = T.sum() #for total array
# et = 1
print("Total efficiency:",'\n',et)

'''Conversion Coefficients'''
astart = Tline+1
aend = astart + w
# print("Acaps", astart, aend)
alpha = np.array(PeakData[astart:aend])
print("Conversion coefficients:",'\n',alpha)
###alpha = np.ones((4,4))*0 #no conversion coefficients for toy system

'''Number of detectors'''
nline = aend
v = (PeakData[nline])
V = v.sum()
print('Number of Detectors', '\n', V)

'''Energy Levels (keV)'''
# Creates empty matrix of appropriate dimensions, and reads in data from line of text file
Energies = np.zeros((w,w))
length_end = w+1
eline = nline+1
# print(length_end)
for i in range(0,w):
# creates empty vector
    v=0
    for j in range(0,w):
#         Defines energy drops
        k = PeakData[eline,i]-PeakData[eline,j]
        j=j+1
        v=np.append(v,k)
#     Ensures that matrix only contains one copy of each value
    for d in range(0,len(v)):
        if v[d] < 0:
            v[d]=0
#     Adds each vector to empty matrix
    Energies[i]=np.array(v[1:length_end])
# Final energy levels (keV)
print("Energy levels:",'\n',Energies)

'''Measured Peaks'''
MPstart = eline+1
MPend = MPstart + w
# print("MPcaps", MPstart, MPend)
S = np.array(PeakData[MPstart:MPend])
print("Measured Peaks:",'\n',S)

'''Peak Efficiencies'''
# Round energy levels to nearest integer
ep = np.rint(Energies)
# print(P)
for i in range(0,len(ep[0])):
    for j in range(0,len(ep[0])):
        if np.not_equal(ep[i,j],0)==True:
            d=ep[i,j]
#             Change D type to integer and value to reflect line number in TRIUMF data 
            D=d.astype(int)-9
#             Change array value to peak efficiency for specified energy
            ep[i,j] = Efficiencies[D,1]
print("Peak efficiencies:",'\n',ep)

Source disintegration rate: 
 100000.0
Total efficiency: 
 0.4
Conversion coefficients: 
 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Number of Detectors 
 64.0
Energy levels: 
 [[    0.        0.        0.        0.   ]
 [ 1332.508     0.        0.        0.   ]
 [ 2158.61    826.102     0.        0.   ]
 [ 2505.748  1173.24    347.138     0.   ]]
Measured Peaks: 
 [[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.06888560e+04   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00821892e-01   1.16612795e+00   0.00000000e+00   0.00000000e+00]
 [  1.95306310e+01   1.15479991e+04   1.91075843e+00   0.00000000e+00]]
Peak efficiencies: 
 [[ 0.          0.          0.          0.        ]
 [ 0.10756144  0.          0.          0.        ]
 [ 0.07667133  0.14371242  0.          0.        ]
 [ 0.0676444   0.11635693  0.25770852  0.        ]]


In [11]:
'''Matrix building (eqs. 4-5)'''
X = np.zeros((w,w))
for i in range(0,len(ep[0])):
    for j in range(0,len(ep[0])):
        if np.not_equal(ep[i,j],0)==True:
            X[i]=S[i]/ep[i]
print(X)
    
    
    

[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  9.93744204e+04              nan              nan              nan]
 [  1.31498817e+00   8.11431599e+00              nan              nan]
 [  2.88725007e+02   9.92463401e+04   7.41441691e+00              nan]]


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  
